# Generated by Django 2.2 on 2020-01-23 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200123_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='dokita_id',
            new_name='dokita',
        ),
    ]
